version: "3"
x-py-common:
  &py-common
  build: .
services:
  datawarehouse:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
  dbt:
    <<: *py-common
    working_dir: /workspace/mydbt
    ports:
      - 9090:8080
  airflow:
    <<: *py-common
    working_dir: /workspace/airflow
    entrypoint: airflow standalone
    ports:
      - 8080:8080
  streamlit:
    <<: *py-common
    working_dir: /workspace/streamlit_app
    entrypoint: streamlit hello --server.port 8080
    ports:
      - 7070:8080
  notebook:
    <<: *py-common
    working_dir: /workspace/notebook
    entrypoint: >
      jupyter-lab
      --allow-root
      --ip=0.0.0.0
      --port=8888
      --no-browser
      --NotebookApp.token=''
      --notebook-dir=/workspace/notebook
    ports:
      - 8888:8888
